export default [
  {
    name: 'label',
    label: 'Label',
    type: 'text',
    placeholder: 'Give This Test A Label',
    defaultValue: 'Backtest Example',
    width: 'w-1/2',
  },
  {
    name: 'custom',
    label: 'Custom Backtester',
    type: 'checkbox',
    value: 'custom',
    width: 'w-1/2',
  },
  { name: 'start', label: 'Start Time', type: 'datetime-local', width: 'w-1/2' },
  { name: 'end', label: 'End Time', type: 'datetime-local', width: 'w-1/2' },
  {
    name: 'funds',
    label: 'Starting Funds In USD',
    type: 'number',
    placeholder: 'Funds in USD',
    defaultValue: '5000',
    width: 'w-1/2',
    min: '1000',
    max: '100000000',
  },
  {
    name: 'granularity',
    label: 'Cycle Granularity',
    type: 'number',
    placeholder: 'Heartbeat granularity in seconds',
    defaultValue: '60',
    width: 'w-1/2',
    min: '1',
    max: '2000000',
  },
  {
    name: 'description',
    label: 'Description',
    type: 'textarea',
    placeholder: 'Summary or description of backtest',
    width: 'w-full',
  },
]
