export const APP_READY = 'APP_READY'
export const ALL_WINDOWS_CLOSED = 'ALL_WINDOWS_CLOSED'

export const MAIN_WINDOW_ACTIVATED = 'MAIN_WINDOW_ACTIVATED'
export const STRATEGY_WINDOW_EXISTS = 'STRATEGY_WINDOW_EXISTS'

export const MIGRATION_REFRESHED = 'MIGRATION_REFRESHED'
export const MIGRATION_REFRESH_FAILED = 'MIGRATION_REFRESH_FAILED'
export const MIGRATION_REFRESH_NULLED = 'MIGRATION_REFRESH_NULLED'
export const MIGRATION_ROLLEDBACK = 'MIGRATION_ROLLEDBACK'
export const MIGRATION_ROLLBACK_FAILED = 'MIGRATION_ROLLBACK_FAILED'
export const MIGRATION_ROLLBACK_NULLED = 'MIGRATION_ROLLBACK_NULLED'

export const STRATEGY_DIR_LINK_SET = 'STRATEGY_DIR_LINK_SET'
export const STRATEGY_DIR_LINK_NOT_SET = 'STRATEGY_DIR_LINK_NOT_SET'
export const NEW_STRATEGY_BOOTSTRAPPED = 'NEW_STRATEGY_BOOTSTRAPPED'
export const NEW_STRATEGY_BOOTSTRAPPED_FAILED = 'NEW_STRATEGY_BOOTSTRAPPED_FAILED'
export const STRATEGY_LATENT = 'STRATEGY_LATENT'
export const STRATEGY_ACTIVE = 'STRATEGY_ACTIVE'
export const STRATEGY_DELETED = 'STRATEGY_DELETED'

export const ERROR_GETTING_BACKTEST_HISTORY = 'ERROR_GETTING_BACKTEST_HISTORY'
export const SUCCESS_STARTING_BACKTEST = 'SUCCESS_STARTING_BACKTEST'
export const ERROR_STARTING_BACKTEST = 'ERROR_STARTING_BACKTEST'
