DROP TABLE IF EXISTS settings;
DROP TABLE IF EXISTS logs;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS test_orders;
DROP TABLE IF EXISTS backtests;
DROP TABLE IF EXISTS backtesters;
DROP TABLE IF EXISTS strategymetas;
DROP TABLE IF EXISTS strategies;
